# CodeRabbit Configuration for Bantuaku
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en-US"
early_access: false

reviews:
  # Review profile: "chill" for standard reviews, "assertive" for detailed feedback
  profile: "chill"
  
  # Don't request changes automatically, just provide suggestions
  request_changes_workflow: false
  
  # Enable high-level summary and review status
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  
  # Auto-review on PR creation
  auto_review:
    enabled: true
    drafts: false
    # Review PRs targeting all branches (not just main/master)
    target_branches: ["*"]
  
  # Path filters - focus on source code, exclude build artifacts
  path_filters:
    - "backend/**/*.go"
    - "frontend/src/**/*.{ts,tsx,js,jsx}"
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/.next/**"
    - "!**/vendor/**"
    - "!**/*.min.js"
    - "!**/*.bundle.js"
    - "!**/go.sum"
    - "!**/*.test.go"
    - "!**/*_test.go"
  
  # Path-specific instructions for different file types
  path_instructions:
    # Go backend instructions
    - path: "backend/**/*.go"
      instructions: |
        Review Go code following these guidelines:
        - Follow Go best practices and idioms
        - Check for error handling (never ignore errors)
        - Ensure proper context usage for cancellation
        - Review for potential race conditions
        - Check for SQL injection vulnerabilities
        - Verify proper use of goroutines and channels
        - Ensure proper resource cleanup (defer statements)
        - Check for nil pointer dereferences
        - Review API security (authentication, authorization)
        - Ensure proper input validation
        - Check for sensitive data exposure in logs
        - Follow RESTful API conventions
        
    # React/TypeScript frontend instructions
    - path: "frontend/src/**/*.{ts,tsx}"
      instructions: |
        Review React and TypeScript code following these guidelines:
        - Follow React best practices (hooks, component structure)
        - Check for TypeScript type safety
        - Review for security vulnerabilities (XSS, CSRF)
        - Ensure proper error handling and loading states
        - Check for memory leaks (useEffect cleanup)
        - Review accessibility (a11y) best practices
        - Ensure proper state management (Zustand usage)
        - Check for performance optimizations (memoization, lazy loading)
        - Verify proper API error handling
        - Check for sensitive data in client-side code
        - Ensure proper form validation
        - Review component reusability and prop types
        - Check for unused imports and dead code
        
    # JavaScript files (if any)
    - path: "frontend/src/**/*.{js,jsx}"
      instructions: |
        Review JavaScript code following these guidelines:
        - Follow modern JavaScript best practices (ES6+)
        - Check for security vulnerabilities
        - Ensure proper error handling
        - Review for performance issues
        - Check for accessibility concerns

  # Tool configurations
  tools:
    # ESLint for JavaScript/TypeScript
    eslint:
      enabled: true
      config_file: "frontend/.eslintrc.json"
    
    # Gitleaks for secret detection
    gitleaks:
      enabled: true
    
    # Go linter (golangci-lint if available)
    golangci:
      enabled: true

chat:
  # Enable auto-reply to comments
  auto_reply: true

# Code generation settings (if needed)
code_generation:
  docstrings:
    path_instructions:
      - path: "backend/**/*.go"
        instructions: |
          Generate Go docstrings following Go documentation conventions.
          Use proper formatting with function name, parameters, and return values.
          End with "Auto-generated by CodeRabbit."
      
      - path: "frontend/src/**/*.{ts,tsx}"
        instructions: |
          Generate TypeScript/React docstrings using JSDoc format.
          Include @param, @returns, and @example tags where appropriate.
          End with "Auto-generated by CodeRabbit."
